# Generated by Django 4.2.6 on 2024-09-13 19:43

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Perm = apps.get_model('auth', 'Permission')

    for p in list(Perm.objects.all()):
        #print("p: ", p)
        pass

    #exit()
    admin_perm_names = [
        'add_user', 'change_user', 'delete_user', 'view_user' # user
    ]
    perms = Perm.objects.filter(codename__in=admin_perm_names).all()
    group, _ = Group.objects.get_or_create(name='admin')
    group.permissions.set(perms)
    group.save()

    consultant_perm_names = [
        'view_comment', 'add_comment',  # comment
        'view_profile', 
        'view_profilefile',
        'view_skill'
    ]
    perms = Perm.objects.filter(codename__in=consultant_perm_names).all()
    group, _ = Group.objects.get_or_create(name='consultant')
    group.permissions.set(perms)
    group.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
