# Generated by Django 4.2.16 on 2024-10-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0002_training"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="trainings",
            field=models.ManyToManyField(related_name="trainings", to="config.skill"),
        ),
    ]
