# Generated by Django 4.2.6 on 2024-08-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_delete_skill_alter_profile_skills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileFile',
        ),
    ]
