# Generated by Django 4.2.16 on 2024-10-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0002_training"),
        ("profiles", "0002_profile_trainings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="trainings",
            field=models.ManyToManyField(
                related_name="trainings", to="config.training"
            ),
        ),
    ]
