# Generated by Django 4.2.16 on 2024-10-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_profile_trainings"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
