# Generated by Django 4.2.16 on 2024-10-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_profile_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birthday",
            field=models.CharField(default="", max_length=50),
        ),
    ]
