# Generated by Django 4.2.16 on 2024-12-03 10:59

from django.db import migrations


def create_initial_data(apps, schema_editor):
    # Get models
    Skill = apps.get_model("config", "Skill")
    State = apps.get_model("config", "State")
    Training = apps.get_model("config", "Training")

    # Create initial Skills
    skills = ["CACES 3", "CACES 9", "CACES A", "CACES B", "Chaudronnier",
              "Electromécanicien", "Hab elec B0", "Hab elec B1", "Hab elec B2",
              "Hab méc M1", "Hab méc M2", "Manutentionnaire", "Monteur", "Monteur au plan",
              "Mécanicien", "Mécanicien monteur", "Peintre", "Permis B", "Permis pont", "Soudeur Arc",
              "Soudeur Arc - Confirmé", "Soudeur Arc - Débutant", "Soudeur Arc - Pointe", "Soudeur Semi",
              "Soudeur Semi - Confirmé", "Soudeur Semi - Débutant", "Soudeur Semi - Pointe", "Soudeur TIG",
              "Soudeur TIG - Confirmé", "Soudeur TIG - Débutant", "Soudeur TIG - Pointe", "Technicien de maintenance",
              "Tuyauteur"]
    for skill_name in skills:
        Skill.objects.get_or_create(name=skill_name)

    # Create initial States
    states = ["Traité", "A contacter", "A traiter",
              "Embauché", "Non retenu", "Retenu"]
    for state_name in states:
        State.objects.get_or_create(name=state_name)

    # Create initial Trainings
    trainings = ["CACES 3", "CACES 9", "CACES A (nacelle ciseau)", "CACES B (nacelle bras articulé)",
                 "Habilitation mécanique M1", "Habilitation mécanique M2"]
    for training_name in trainings:
        Training.objects.get_or_create(name=training_name)


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0002_training"),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
